### ISSUE TITLE
Should not insert spans into tables even if there is white space

### ISSUE THREAD

**Issue by RacingTadpole** [mikenikles/html-to-react#30] opened 2016-04-04 02:16 UTC
Eg. this test fails (note the space between `tbody` and `tr`; a new line has the same effect):

        it('should not insert spans into tables even if there is white space', function() {
            var htmlInput = '<table><tbody> <tr><td>x</td><td>3</td></tr></tbody></table>';

            var reactComponent = parser.parse(htmlInput);
            var reactHtml = ReactDOMServer.renderToStaticMarkup(reactComponent);

            assert.equal(reactHtml, htmlInput);
        });

with the warning:

```Error: Warning: validateDOMNesting(...): <span> cannot appear as a child of <tbody>. See tbody > span.```

**Comment by mikenikles** [comment] 2016-04-30 19:37
@RacingTadpole That doesn't seem to be an issue anymore in the latest `master`. I'm closing this for now, but please feel free to re-open if it still occurs for you.

**Closed by mikenikles** 2016-04-30 19:37 UTC

**Comment by RacingTadpole** [comment] 2016-09-20 07:01
Thanks @mikenikles. I agree, this test passes on the current master (1.0.0). 
Interestingly it also produces a warning:

```Warning: validateDOMNesting(...): <span> cannot appear as a child of <tbody>. See tbody > span.```

...so the issue is still real for me. But I'm happy to delegate the problem to a white-space-removing library, if one exists - as suggested by @aknuds1 in #31.

**Comment by aknuds1** [comment] 2016-09-20 08:12
@RacingTadpole Aha, I see the warning now, except it doesn't mention `<span>` for me, but instead 'Whitespace text nodes'. I'm using React 15.3.2.

    Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <table>. Make sure you don't have any extra whitespace between tags on each line of your source code. See table > #text.

I guess this is a real concern when translating to React then.

**Comment by aknuds1** [comment] 2016-09-20 08:50
How do you guys think this should be addressed? Is the best solution to avoid creating whitespace text nodes within tables as React is warning of here?

**Comment by aknuds1** [comment] 2016-09-20 08:50
How do you guys think this should be addressed? Is the best solution to avoid creating whitespace text nodes within tables as React is warning of here?

**Comment by RacingTadpole** [comment] 2016-09-20 23:41
@alexgilleran or @kring - do either of you guys have an opinion on how/whether html-to-react should filter whitespace?

**Comment by AlexGilleran** [comment] 2016-09-21 02:07
I think the problem is as such:

- Within HTML there's really two kinds of white space - meaningless white space that goes in between tags to make the HTML more readable and actual text whitespace that goes between words
- HTML2React is currently interpreting all white space as text whitespace 
- React thinks this means you're putting text in places it shouldn't be (like between `<table>` and `<tr>`. It used to render this as `<span>` which was bad but the browser could ignore it, now it renders it as `<-- reactid etc` which is better but still not perfect.

The only really neat way I can think of to solve this is to make it so that whitespace is removed except when the text is an immediate child of a tag that supports it, like `<div>`, `<span>`, `<p>` etc.

**Comment by aknuds1** [comment] 2016-09-21 09:37
Could someone come up with test cases for the desired behaviour? @AlexGilleran?
